Pandas Challenges
Data Merging: Merge the two datasets using the adm4_pcode column to combine hazard data with location details.

Hazard Risk Analysis: Find the top 10 administrative areas (barangays) with the highest percentage of high-risk flood hazards (100-year and 25-year floods).

Landslide Hazard Distribution: Calculate the average percentage of areas affected by landslides (low, medium, high) per region (adm1_en).

Temporal Analysis: Group the flood hazard data by year (extract from date) and compute the average flood risk trends over time.

Filtering Data: Retrieve records where more than 50% of the area is classified as high-risk for landslides.

Brgy Area Adjustment: Create a new column that calculates the estimated absolute area (in sq. km) affected by each hazard, using brgy_total_area.

Matplotlib Challenges
Flood Hazard Visualization: Create a bar chart showing the total percentage of flood-prone areas per region (adm1_en).

Landslide Hazard Map: Use a heatmap to show the distribution of landslide hazard severity across different administrative levels (adm1_en, adm2_en).

Time Series Analysis: Plot a line graph showing the trend of high-risk flood hazards over time.

Comparison of Hazard Types: Create a stacked bar chart comparing the proportion of landslide and flood hazards in different provinces (adm2_en).

Top Risk Areas: Use a scatter plot to visualize the relationship between barangay size and hazard risk percentage.

In [5]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

df1 = pd.read_csv("location.csv")
df2 = pd.read_csv("project_noah_hazards (1).csv")

In [8]:
df1.head()

,Unnamed: 0,adm1_en,adm1_pcode,adm2_en,adm2_pcode,adm3_en,adm3_pcode,adm4_en,adm4_pcode,brgy_total_area
0,0,Region I,PH010000000,Pangasinan,PH015500000,Dagupan City,PH015518000,Lomboy,PH015518016,1.0216
1,1,Region I,PH010000000,Pangasinan,PH015500000,Dagupan City,PH015518000,Tapuac,PH015518031,1.0440
2,2,Region I,PH010000000,Pangasinan,PH015500000,Dagupan City,PH015518000,Pantal,PH015518022,3.2625
3,3,Region I,PH010000000,Pangasinan,PH015500000,Dagupan City,PH015518000,Barangay I (T. Bugallon),PH015518024,0.1814
4,4,Region III,PH030000000,Nueva Ecija,PH034900000,Palayan City,PH034919000,Imelda Valley,PH034919017,6.3369

In [10]:
df2.head()

,uuid,adm4_pcode,date,freq,pct_area_flood_hazard_100yr_low,pct_area_flood_hazard_100yr_med,pct_area_flood_hazard_100yr_high,pct_area_flood_hazard_25yr_low,pct_area_flood_hazard_25yr_med,pct_area_flood_hazard_25yr_high,pct_area_flood_hazard_5yr_low,pct_area_flood_hazard_5yr_med,pct_area_flood_hazard_5yr_high,pct_area_landslide_hazard_low,pct_area_landslide_hazard_med,pct_area_landslide_hazard_high
0,PNHZD000000,PH050506053,2015-01-01,S,18.7712,0.6885,0.0907,2.0355,0.5726,0.0593,1.3750,0.3818,0.0356,0.0000,0.0000,0.0000
1,PNHZD000001,PH050506056,2015-01-01,S,3.3062,5.8337,6.5147,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,10.1344,7.9272,1.9193
2,PNHZD000002,PH050506072,2015-01-01,S,4.4233,1.8771,0.0000,3.2703,1.7898,0.0000,2.4791,1.1932,0.0000,0.0000,0.0000,0.0000
3,PNHZD000003,PH050506020,2015-01-01,S,7.0334,68.6624,22.8292,17.2611,70.5887,5.9013,20.8956,51.5883,0.0000,0.0000,0.0000,0.0000
4,PNHZD000004,PH050506051,2015-01-01,S,17.2954,5.9285,0.1185,13.7895,4.5504,0.0476,9.6298,2.9822,0.0406,0.0000,0.0000,0.0000

In [7]:
# Data Merging: Merge the two datasets using the adm4_pcode column to combine hazard data with location details.

merge_data = df2.merge(df1, on = "adm4_pcode", suffixes = ("_left","_right"))

In [12]:
merge_data

,uuid,adm4_pcode,date,freq,pct_area_flood_hazard_100yr_low,pct_area_flood_hazard_100yr_med,pct_area_flood_hazard_100yr_high,pct_area_flood_hazard_25yr_low,pct_area_flood_hazard_25yr_med,pct_area_flood_hazard_25yr_high,...,pct_area_landslide_hazard_high,Unnamed: 0,adm1_en,adm1_pcode,adm2_en,adm2_pcode,adm3_en,adm3_pcode,adm4_en,brgy_total_area
0,PNHZD000000,PH050506053,2015-01-01,S,18.7712,0.6885,0.0907,2.0355,0.5726,0.0593,...,0.0000,6,Region V,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 45 - Dita (Bgy. 51),0.8428
1,PNHZD000001,PH050506056,2015-01-01,S,3.3062,5.8337,6.5147,0.0000,0.0000,0.0000,...,1.9193,7,Region V,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 62 - Homapon (Bgy. 55),7.0818
2,PNHZD000002,PH050506072,2015-01-01,S,4.4233,1.8771,0.0000,3.2703,1.7898,0.0000,...,0.0000,8,Region V,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 10 - Cabugao,0.0335
3,PNHZD000003,PH050506020,2015-01-01,S,7.0334,68.6624,22.8292,17.2611,70.5887,5.9013,...,0.0000,9,Region V,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 23 - Imperial Court Subd. (Pob.),0.0621
4,PNHZD000004,PH050506051,2015-01-01,S,17.2954,5.9285,0.1185,13.7895,4.5504,0.0476,...,0.0000,10,Region V,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 40 - Cruzada (Bgy. 52),1.4442
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,PNHZD00036A,PH097332030,2015-01-01,S,6.5297,15.6041,7.3458,0.0000,0.0000,0.0000,...,0.5461,825,Region IX,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Guisao,4.0623
875,PNHZD00036B,PH097332057,2015-01-01,S,8.1345,11.1257,0.0625,0.0000,0.0000,0.0000,...,0.0010,826,Region IX,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Panubigan,5.1799
876,PNHZD00036C,PH097332022,2015-01-01,S,10.9345,21.0155,1.8109,0.0000,0.0000,0.0000,...,0.1417,827,Region IX,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Cawit,3.3696
877,PNHZD00036D,PH097332081,2015-01-01,S,3.4650,3.2554,5.0526,1.5103,1.3426,2.1107,...,8.6049,828,Region IX,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Tagasilay,17.8318
878,PNHZD00036E,PH097332103,2015-01-01,S,15.8544,11.9953,2.0936,12.9809,9.4369,1.4377,...,2.0614,829,Region IX,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Victoria,10.1352

In [30]:
# Hazard Risk Analysis: Find the top 10 administrative areas (barangays) with the highest percentage of high-risk flood hazards (100-year and 25-year floods).

barangay_report = merge_data.groupby(["adm4_en"])[["pct_area_flood_hazard_100yr_high","pct_area_flood_hazard_25yr_high"]].mean()
barangay_report["ranking"] = barangay_report["pct_area_flood_hazard_100yr_high"] + barangay_report["pct_area_flood_hazard_25yr_high"]
barangay_report.sort_values(by = ["ranking"],ascending = False,inplace = True)
barangay_report.head(5)

,pct_area_flood_hazard_100yr_high,pct_area_flood_hazard_25yr_high,ranking
adm4_en,,,
Barangay 17 (Pob.),95.1448,94.9052,190.0500
Barangay 15 (Pob.),90.4153,85.4485,175.8638
Consolacion,92.8972,81.1002,173.9974
Barangay 13 (Pob.),82.6511,76.6016,159.2527
Popolon Pagas,79.3347,65.5815,144.9162

In [23]:
# Landslide Hazard Distribution: Calculate the average percentage of areas affected by landslides (low, medium, high) per region (adm1_en).

regional = merge_data.groupby(["adm1_en"])[["pct_area_landslide_hazard_high","pct_area_landslide_hazard_med","pct_area_landslide_hazard_low"]].mean()

regional

,pct_area_landslide_hazard_high,pct_area_landslide_hazard_med,pct_area_landslide_hazard_low
adm1_en,,,
National Capital Region,0.010228,0.076988,0.132502
Region I,0.000000,0.000000,0.000000
Region III,5.871211,5.042716,3.272705
Region IX,6.157449,16.813581,6.161425
Region V,3.506990,4.306621,3.429630
Region VI,0.002882,0.003094,0.003366
Region VII,0.124081,2.226130,1.310400
Region VIII,5.624552,4.283549,1.506725
Region X,4.505055,13.183669,2.886518
Region XI,7.086630,11.470481,3.475944

In [63]:
# Temporal Analysis: Group the flood hazard data by year (extract from date) and compute the average flood risk trends over time.

merge_data["date"] = pd.to_datetime(merge_data["date"])
merge_data["Year"] = merge_data["date"].dt.year
merge_data["Months"] = merge_data["date"].dt.month_name()
merge_data


trend_report = merge_data.groupby(["Months"])[["pct_area_landslide_hazard_high","pct_area_landslide_hazard_med","pct_area_landslide_hazard_low"]].mean()

trend_report

,pct_area_landslide_hazard_high,pct_area_landslide_hazard_med,pct_area_landslide_hazard_low
Months,,,
January,3.887111,6.717725,2.323229

In [67]:
year_report = merge_data.groupby(["Year"])[["pct_area_landslide_hazard_high","pct_area_landslide_hazard_med","pct_area_landslide_hazard_low"]].mean()

year_report

,pct_area_landslide_hazard_high,pct_area_landslide_hazard_med,pct_area_landslide_hazard_low
Year,,,
2015,3.887111,6.717725,2.323229

In [19]:
# Filtering Data: Retrieve records where more than 50% of the area is classified as high-risk for landslides.

report_high = merge_data[merge_data["pct_area_landslide_hazard_high"] > 50].sort_values(by = ["pct_area_landslide_hazard_high"])

report_high

,uuid,adm4_pcode,date,freq,pct_area_flood_hazard_100yr_low,pct_area_flood_hazard_100yr_med,pct_area_flood_hazard_100yr_high,pct_area_flood_hazard_25yr_low,pct_area_flood_hazard_25yr_med,pct_area_flood_hazard_25yr_high,...,pct_area_landslide_hazard_high,Unnamed: 0,adm1_en,adm1_pcode,adm2_en,adm2_pcode,adm3_en,adm3_pcode,adm4_en,brgy_total_area
488,PNHZD0001E8,PH083747132,2015-01-01,S,2.6114,5.1811,3.8063,1.8272,2.8899,0.6261,...,50.2374,185,Region VIII,PH080000000,Leyte,PH083700000,Tacloban City,PH083747000,Barangay 98 (Camansinay),8.0852
248,PNHZD0000F8,PH112402029,2015-01-01,S,2.0112,4.0376,5.4338,0.0000,0.0000,0.0000,...,52.6654,716,Region XI,PH110000000,Davao del Sur,PH112400000,Davao City,PH112402000,Carmen,7.8821
101,PNHZD000065,PH112402067,2015-01-01,S,0.8983,4.1868,8.0411,0.0000,0.0000,0.0000,...,57.2318,99,Region XI,PH110000000,Davao del Sur,PH112400000,Davao City,PH112402000,Malamba,102.9197
171,PNHZD0000AB,PH112402901,2015-01-01,S,1.2152,3.8918,3.0430,0.5623,0.4114,0.4545,...,57.8851,411,Region XI,PH110000000,Davao del Sur,PH112400000,Davao City,PH112402000,Mount Apo National Park under Jurisdiction of ...,226.8714
229,PNHZD0000E5,PH112402183,2015-01-01,S,0.7320,4.0672,6.1306,0.0000,0.0000,0.0000,...,61.4312,697,Region XI,PH110000000,Davao del Sur,PH112400000,Davao City,PH112402000,Gumitan,55.7957
559,PNHZD00022F,PH083747026,2015-01-01,S,2.7604,5.1184,2.4111,0.3489,0.5526,0.2566,...,67.6527,653,Region VIII,PH080000000,Leyte,PH083700000,Tacloban City,PH083747000,Barangay 107 (Santa Elena),9.4276
23,PNHZD000017,PH050506061,2015-01-01,S,8.7401,6.0987,2.0501,0.0000,0.0000,0.0000,...,67.8127,153,Region V,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 50 - Padang (Bgy. 60),11.3811
116,PNHZD000074,PH112402178,2015-01-01,S,0.5842,4.2842,2.8384,0.0000,0.0000,0.0000,...,70.0029,114,Region XI,PH110000000,Davao del Sur,PH112400000,Davao City,PH112402000,Buda,19.4714
554,PNHZD00022A,PH083747008,2015-01-01,S,0.6108,0.9840,0.0000,0.0000,0.0000,0.0000,...,70.4842,648,Region VIII,PH080000000,Leyte,PH083700000,Tacloban City,PH083747000,Nula-tula (Bgys. 3 & 3A),0.2783

In [77]:
# Brgy Area Adjustment: Create a new column that calculates the estimated absolute area (in sq. km) affected by each hazard, using brgy_total_area.
# (area * hazard)/100
area_effect = merge_data.copy()

area_effect["Area_affect_100yr_flood"] = area_effect["pct_area_flood_hazard_100yr_high"] / 100 * area_effect["brgy_total_area"]
area_effect["Area_effect_25yr_flood"] = area_effect["pct_area_flood_hazard_25yr_high"] / 100 * area_effect["brgy_total_area"]
area_effect["Area_effect_land_slide"] = area_effect["pct_area_landslide_hazard_high"] / 100 * area_effect["brgy_total_area"]


area_effect

,uuid,adm4_pcode,date,freq,pct_area_flood_hazard_100yr_low,pct_area_flood_hazard_100yr_med,pct_area_flood_hazard_100yr_high,pct_area_flood_hazard_25yr_low,pct_area_flood_hazard_25yr_med,pct_area_flood_hazard_25yr_high,...,adm1_pcode,adm2_en,adm2_pcode,adm3_en,adm3_pcode,adm4_en,brgy_total_area,Area_affect_100yr_flood,Area_effect_25yr_flood,Area_effect_land_slide
0,PNHZD000000,PH050506053,2015-01-01,S,18.7712,0.6885,0.0907,2.0355,0.5726,0.0593,...,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 45 - Dita (Bgy. 51),0.8428,0.000764,0.000500,0.000000
1,PNHZD000001,PH050506056,2015-01-01,S,3.3062,5.8337,6.5147,0.0000,0.0000,0.0000,...,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 62 - Homapon (Bgy. 55),7.0818,0.461358,0.000000,0.135921
2,PNHZD000002,PH050506072,2015-01-01,S,4.4233,1.8771,0.0000,3.2703,1.7898,0.0000,...,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 10 - Cabugao,0.0335,0.000000,0.000000,0.000000
3,PNHZD000003,PH050506020,2015-01-01,S,7.0334,68.6624,22.8292,17.2611,70.5887,5.9013,...,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 23 - Imperial Court Subd. (Pob.),0.0621,0.014177,0.003665,0.000000
4,PNHZD000004,PH050506051,2015-01-01,S,17.2954,5.9285,0.1185,13.7895,4.5504,0.0476,...,PH050000000,Albay,PH050500000,Legazpi City,PH050506000,Bgy. 40 - Cruzada (Bgy. 52),1.4442,0.001711,0.000687,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,PNHZD00036A,PH097332030,2015-01-01,S,6.5297,15.6041,7.3458,0.0000,0.0000,0.0000,...,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Guisao,4.0623,0.298408,0.000000,0.022184
875,PNHZD00036B,PH097332057,2015-01-01,S,8.1345,11.1257,0.0625,0.0000,0.0000,0.0000,...,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Panubigan,5.1799,0.003237,0.000000,0.000052
876,PNHZD00036C,PH097332022,2015-01-01,S,10.9345,21.0155,1.8109,0.0000,0.0000,0.0000,...,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Cawit,3.3696,0.061020,0.000000,0.004775
877,PNHZD00036D,PH097332081,2015-01-01,S,3.4650,3.2554,5.0526,1.5103,1.3426,2.1107,...,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Tagasilay,17.8318,0.900970,0.376376,1.534409
878,PNHZD00036E,PH097332103,2015-01-01,S,15.8544,11.9953,2.0936,12.9809,9.4369,1.4377,...,PH090000000,Zamboanga del Sur,PH097300000,Zamboanga City,PH097332000,Victoria,10.1352,0.212191,0.145714,0.208927

In [67]:
area_effect["pct_area_flood_hazard_100yr_high"] / 100 * area_effect["brgy_total_area"]

adm4_en
Abeto Mirasol Taft South (Quirino Abeto)    0.000100
Acacia                                      0.467551
Addition Hills                              0.042130
Agdao                                       0.000000
Aguinaldo                                   0.000000
                                              ...
Wines                                       0.310934
Yulo Drive                                  0.041251
Yulo-Arroyo                                 0.000000
Zambowood                                   0.194642
Zamora-Melliza                              0.000000
Length: 870, dtype: float64

In [ ]:
pd.to_csv("")